"""Added account and account tables

Revision ID: 602e2bc6b33d
Revises: f84123684462
Create Date: 2022-06-01 23:56:15.006306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602e2bc6b33d'
down_revision = 'f84123684462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
